{% set version = "1.3.6" %}

package:
  name: simplekml
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/simplekml/simplekml-{{ version }}.tar.gz
  sha256: cda687be2754395fcab664e908ebf589facd41e8436d233d2be37a69efb1c536

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - simplekml
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://www.simplekml.com/en/latest/
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: A Simple KML creator

extra:
  recipe-maintainers:
    - ocefpaf
