travis:
  secure:
    BINSTAR_TOKEN: G/ZapifuKuSOdjiXvR+YwM/HHOCPjD90xbU4pYBZJKxnGwgsaptB8VhDr/jF7D1Bl/yL2rLgkdLCbW8sg/dPu5vfSslwQ6bJNJxcqnYQgAskVwf1iJNzGTRjFpECFNf8Gb0x5MxyjN9Q0EGWomZAt7xwmbDTcWTPyNZGE54NQGvKGF05eGgqFvR+jOPPzSfLwSQDdFrnS4u284cNPXDNeT6dq5fwIJx2IaoxJQ0KZPh1snp8RxGAQs4UOE4AK9fihqF0R76lqX5UcHZi/1tKpaPxBx4lSRp4j8R+akitB+eNtEKv9m9ua8i7iBTlSyXmFr/pEfo7Z/2t8jFv1Bjm72mTo6zwwFPe5Zih+PM7SuHN2IzIemrQtPIi+sOe5Otf7ogKapbriS6+M/OGgN1Ny0PmV4Krg2MzKg2LehWFISkX71skz0HIpk3IlN4oaGEQpgHRJf7ZCgS7fJDggUhNUKNnQ6MRCQWpTIjB9BtYNGCflr9zD6nHKTJ8ZYckAY06y9nmKFVTEsmZGR5ep39WyQrxOfaYYJOeoAWbGTdcmqo5PjTy3qnmYJ6kKz7XNo/P35G9x15w4ZU2ExdLHJNnmSjp3mbTqkfKdopsZdjgq0u3S7ZuCThQirqNtTwnnh4SznShThwZcg9ar3+33vZ71HofpoGGikFyE88Xsvgf9Ls=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
